# OSM Lab: Computation Problem Set 1
## Rebekah Dix
### June 26th, 2018

# Lab 4: Introduction to NumPy

## Problem 1

In [1]:
import numpy as np

def multiplyMat():
    A = np.array([[3, -1, 4], [1, 5, -9]])
    B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
    return A @ B

AB = multiplyMat()
print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


## Problem 2

In [2]:
def problem2():
    A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
    result = (-1) * (A @ A @ A) + 9 * (A @ A) -15 * A
    return result

problem2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 3

In [3]:
def problem3():
    # Create A
    A = np.ones((7,7))
    A = np.triu(A)
    
    # Create B
    B1 = (-1) * np.ones((7,7))
    B1 = np.tril(B1)   
    B2 = (5) * np.ones((7,7))
    B2 = np.triu(B2, 1)    
    B = B1 + B2 
    
    # Calculate matrix product ABA
    result = A @ B @ A
    
    # Change data type to np.int64
    result = result.astype(np.int64)
    
    return result
    
problem3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

## Problem 4

In [4]:
def problem4(a):
    # make a copy of the array
    acopy = np.copy(a)
    # set all negative entries to 0
    indices0 = acopy < 0
    acopy[indices0] = 0
    
    return acopy
  
a = np.array([-3, -4, 5, 9, 0])
problem4(a)

array([0, 0, 5, 9, 0])

## Problem 5

In [5]:
def problem5():
    A = np.array([[0, 2, 4], [1, 3, 5]])
    
    B = 3 * np.ones((3,3))
    B = np.tril(B)
    
    C = np.diag([-2, -2, -2])

    row1 = np.column_stack((np.zeros((3,3)), A.T, np.eye(3)))
    row2 = np.column_stack((A, np.zeros((2,2)), np.zeros((2,3))))
    row3 = np.column_stack((B, np.zeros((3,2)), C))
    
    result = np.vstack((row1, row2, row3))
                      
    return result
problem5()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

## Problem 6

In [6]:
def problem6(A):
    
    i, j = np.shape(A)
    rowSums = np.sum(A, axis=1).reshape((j,1))
    stochA = A / rowSums
    
    return stochA

A = np.array([[1,9], [1, 1]])
problem6(A)

array([[0.1, 0.9],
       [0.5, 0.5]])

## Problem 7

In [7]:
def problem_7():
    grid = np.load("grid.npy")
    
    horizontalMax = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    verticalMax = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rightDiagonalMax = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    leftDiagonalMax = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(horizontalMax, verticalMax, rightDiagonalMax, leftDiagonalMax)
   
problem_7()

70600674

# Lab 2: The Standard Library

## Problem 1

In [8]:
def problem1_2(L):
    return (min(L), max(L), sum(L)/(len(L)))
L = [1, 2, 3, 4]
problem1_2(L)

(1, 4, 2.5)

## Problem 2

In [9]:
# int
a = 3
b = a
b = 1
a == b
print('Integers are mutable: ' + str(a == b))

# str
str1 = 'Rebekah'
str2 = str1
str2 = 'Dix'
str1 == str2
print('Strings are mutable: ' + str(str1 == str2))

# list 
list1 = [1, 2, 3, 4]
list2 = list1
list2[0] = 0
print('Lists are mutable: ' + str(list1 == list2))

# tuple
tuple1 = (1,2)
tuple2 = tuple1
tuple2 += (4,)
print('Tuples are mutable: ' + str(tuple1 == tuple2))

# set
set1 = {3, 4, 5}
set2 = set1
set2.add(6)
print('Sets are mutable: ' + str(set1 == set2))

Integers are mutable: False
Strings are mutable: False
Lists are mutable: True
Tuples are mutable: False
Sets are mutable: True


## Problem 3

Also see calculator.py.

In [10]:
import calculator
from math import sqrt

def problem3_2(a, b):
    h = sqrt(calculator.sumArg(calculator.prodArg(a,a), calculator.prodArg(b,b)))  
    return h

problem3_2(3,4)

5.0

## Problem 4

In [11]:
from itertools import combinations

def problem4_2(A):
    powerSet = []
    for i in range(len(A) + 1):
        addSet = combinations(A,i)
        for item in addSet:
            powerSet.append(set(item))
        
    return powerSet

In [12]:
problem4_2({1, 2, 3})

[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]

## Problem 5

See shut_the_box.py and box.py, which are to be run in the terminal with command line arguments.

# Lab 7: Unit Testing

See functions_ProbSet1.py for the function definitions and test_ProbSet1.py for the required tests.

# Lab 3: Object-Oriented Programming

### Problem 1 and Problem 3

In [13]:
class Backpack:
    """A Backpack object class. Has a name and a list of contents.
    
    Attributes:
        name (str): the name of the backpack's owner.
        contents (list): the contents of the backpack.
        color (str): the color of the backpack
        max_size (int): the maximum number of items the backpack can hold
        
    """

    def __init__(self, name, color, max_size=5):     # This function is the constructor.
        """Set the name and initialize an empty list of contents.
        
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack
            max_size (int): the maximum number of items the backpack can hold, defaults to 5
            
        """
        
        self.name = name          # Initialize some attributes.
        self.contents = []
        self.color = color
        self.max_size = max_size
        
    def __eq__(self, other):
        """Determine if two backpacks are equal. Two backpacks are equal if
        and only if they have the same name, color, and number of contents.
        
        Parameters:
            other (Backpack): the backpack with which we want to see if this
                              backpack is equal to
    
        """
        
        if self.name != other.name:
            return False
        elif self.color != other.color:
            return False
        elif len(self.contents) != len(other.contents):
            return False
        else:
            return True
        
        
    def __str__(self):
        """ This magic method returns th string representation of an object."""
        
        string = str(    "Owner:\t\t" + str(self.name)
                     + "\nColor:\t\t" + str(self.color)
                     + "\nSize:\t\t" + str(len(self.contents))
                     + "\nMax Size:\t" + str(self.max_size)
                     + "\nContents:\t" + str(self.contents))
        
        return string
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents.
        
        Parameters:
            item (str): the object to be added to the backpack
        """
        
        if len(self.contents) >= self.max_size:
            Print("No Room!")
        else:
            self.contents.append(item)     # Use 'self.contents', not just 'contents'.
    
    def take(self, item):
        """Remove 'item' from the backpack's list of contents.
        
        Parameters:
            item (str): the object to be removed from the backpack
        
        """
        self.contents.remove(item)
    
    def dump(self):
        """Reset the contents of the backpack to an empty list."""
        
        self.contents = []   

In [14]:
def test_backpack():
    """This function instantiates and analyzes a Backpack objects."""
    testpack = Backpack("Barry", "black", 10) # Instantiate the object.
    if testpack.name != "Barry":          # Test an attribute.
        print("Backpack.name assigned incorrectly")
    if testpack.color != "black":
        print("Backpack.color assigned incorrectly")
    if testpack.max_size != 10:
        print("Backpack.max_size assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)                # Test a method.
    print("Contents: ", testpack.contents)
    print("Color: ", testpack.color)
    print("Max backpack size: ", testpack.max_size)
    
    print()
    print(testpack)

test_backpack()

Contents:  ['pencil', 'pen', 'paper', 'computer']
Color:  black
Max backpack size:  10

Owner:		Barry
Color:		black
Size:		4
Max Size:	10
Contents:	['pencil', 'pen', 'paper', 'computer']


### Problem 2

In [15]:
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from Backpack class.
    A Jetpack also includes fuel.
    
    Attributes:
        name (str): the name of the jetpacks's owner.
        contents (list): the contents of the jetpacks.
        color (str): the color of the jetpacks
        max_size (int): the maximum number of items the jetpack can hold, defaults to 2
        fuel(int): the amount of fuel the jetpack has, defaults to 10
    
    """
    
    def __init__(self, name, color, max_size=2, fuel=10):
        """Use the Backpack constructor to initialize the name, color,
        and max_size attributes. A Jetpack only holds 2 items by default.

        Parameters:
            name (str): the name of the jetpacks's owner.
            contents (list): the contents of the jetpacks.
            color (str): the color of the jetpacks
            max_size (int): the maximum number of items the jetpack can hold, defaults to 2
            fuel(int): the amount of fuel the jetpack has, defaults to 10
        
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    
    def fly(self, fuel):
        """Accepts an amount of fuel to be burned and decrements 
        the fuel attribute by that amount. If the user tries to burn more fuel than remains, 
        function prints “Not enough fuel!” and does not decrement the fuel.
        
        Parameters:
            fuel (int): the amount of fuel to be burned
        
        """
        
        if fuel > self.fuel:    # if the user tries to burn more fuel than remains
            print("Not enough fuel!")
        else:
            self.fuel -= fuel
        
    def dump(self):   # Override the dump() method.
        """Empties both the contents and fuel tank."""
        self.fuel = 0
        self.contents = []
            

In [16]:
def test_jetpack():
    """This functions instantiates and analyzes a JetPack objects."""
    testjet = Jetpack("Jan", "blue", 10, 100)
    if testjet.name != "Jan":          # Test an attribute.
        print("Backpack.name assigned incorrectly")
    if testjet.color != "blue":
        print("Backpack.color assigned incorrectly")
    if testjet.max_size != 10:
        print("Backpack.max_size assigned incorrectly")
    if testjet.fuel != 100:
        print("Backpack.fuel assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testjet.put(item)  
    print("Contents: ", testjet.contents)
    print("Color: ", testjet.color)
    print("Max jetpack size: ", testjet.max_size)
    print("Current fuel: ", testjet.fuel)
    
    testjet.fly(50)
    print("Fuel after flying: ", testjet.fuel)
    
    testjet.fly(100)
    
    testjet.dump()
    print("Current fuel: ", testjet.fuel)
    print("Contents: ", testjet.contents)
    
test_jetpack()

Contents:  ['pencil', 'pen', 'paper', 'computer']
Color:  blue
Max jetpack size:  10
Current fuel:  100
Fuel after flying:  50
Not enough fuel!
Current fuel:  0
Contents:  []


### Problem 4

In [17]:
class ComplexNumber():
    """A class that represents complex numbers and their operations.
    
    Attributes:
        real (int): an integer representing the real part of a complex number
        imag (int): an integer representing the imaginary part of a complex number
    
    """
    
    def __init__(self, a, b):
        """Set the real and imaginary parts of the complex number.
        
        Parameters:
            a (int): real part of complex number
            b (int): imaginary part of complex number
        """
        
        self.real = a
        self.imag = b
        
    def __str__(self):
        """Return the complex number formatted as a string."""
        
        if self.imag >= 0:
            string = str("(" + str(self.real) + "+" + str(self.imag) + "j)")
        else:
            string = str("(" + str(self.real) + "-" + str(-self.imag) + "j)")
            
        return string

    def __abs__(self):
        """Return the magnitude of the complex number."""
        
        magnitude = math.sqrt(self.real**2 + self.imag**2)
        return magnitude
    
    def __eq__(self, other):
        """Test if two complex numbers are equal. To be equal, they must
        have the same real and imaginary parts.
        
        Parameters:
            other (ComplexNumber): the complex number we want to see if self
            is equal to
        
        """
        
        # must have same real part
        if self.real != other.real:
            return False
        # must have same imaginary part
        elif self.imag != other.imag:
            return False
        else:
            return True
        
    def __add__(self, other):
        """Add two complex numbers.
        
        Parameters:
            other (ComplexNumber): the complex number we want to add
            to self
        
        """
        
        # add real parts
        newReal = self.real + other.real
        # add imaginary parts
        newImag = self.imag + other.imag
        
        return ComplexNumber(newReal, newImag)
    
    def __sub__(self, other):
        """Subtract two complex numbers.
        
        Parameters:
            other (ComplexNumber): the complex number we want to subtract
            from self
        
        """     
        
        # Subtract real parts
        newReal = self.real - other.real
        # Subtract imaginary parts
        newImag = self.imag - other.imag
        
        return ComplexNumber(newReal, newImag)    
    
    def __mul__(self, other):
        """Multiply two  complex numbers.
        
        Parameters:
            other (ComplexNumber): the complex number we want to multiply with self
        
        """
    
        newReal = (self.real * other.real - self.imag * other.imag)
        newImag = (self.real * other.imag + self.imag * other.real)
        
        return ComplexNumber(newReal, newImag)
    
    def __truediv__(self, other):       
        """Divide two  complex numbers.
        
        Parameters:
            other (ComplexNumber): the complex number we want to divide with self
        
        """
        
        if other.real == 0 and other.imag == 0:
            raise ZeroDivisionError("cannot divide by zero")
        
        denom = other.real**2 + other.imag**2
        newReal = (self.real * other.real + self.imag * other.imag) / denom
        newImag = (self.imag * other.real - self.real * other.imag) / denom
        
        return ComplexNumber(newReal, newImag)
        
    
    def conjugate(self):
        """Calculate the complex conjugate of this complex number."""
        
        return ComplexNumber(self.real, -(self.imag))
    
    

In [18]:
def test_ComplexNumber(a, b):
    """This function instantiates and analyzes a ComplexNumber object."""
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
        
    test = ComplexNumber(5, 7)
    print(test + my_cnum)
    print(test * my_cnum)
    print(test / my_cnum)
        
test_ComplexNumber(1, 2)

(6+9j)
(-9+17j)
(3.8-0.6j)


# Lab 6: Exceptions and File Input/Output

### Problem 1

In [20]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                       "digits differ by 2 or more: ")
    try:
        value = int(step_1)
    except ValueError:
        print("You did not enter an integer.")
        
    if len(step_1) != 3:
        raise ValueError("You did not enter a 3-digit integer.")
    
    if abs(int(step_1[0]) - int(step_1[2])) < 2:
        raise ValueError("The first number's first and last digits differ by less than 2") 
          
    step_2 = input("Enter the reverse of the first number, obtained "
                                          "by reading it backwards: ")
    
    reverseString = step_1[::-1]
    if step_2 != reverseString:
        raise ValueError("You did not reverse the first number.")
        
    step_3 = input("Enter the positive difference of these numbers: ")
    
    try:
        value = int(step_3)
    except ValueError:
        print("You did not enter an integer.")
        
    posDiff = abs(int(step_1) - int(reverseString))
    if int(step_3) != posDiff:
        raise ValueError("You did not enter the positive difference of these numbers")
        
    step_4 = input("Enter the reverse of the previous result: ")
    
    reverseString2 = step_3[::-1]
    if step_4 != reverseString2:
        raise ValueError("You did not reverse the third number.")

    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")
    
arithmagic()
    

Enter a 3-digit number where the first and last digits differ by 2 or more: 123
Enter the reverse of the first number, obtained by reading it backwards: 321
Enter the positive difference of these numbers: 198
Enter the reverse of the previous result: 891
198 + 891 = 1089 (ta-da!)


### Problem 2

To test the code below, recall that to cause a KeyboardInterrupt exception in a Jupyter Notebook you must be in command mode and hit the i key twice.

In [21]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    
    try:
        for ind, ii in enumerate(range(int(max_iters))):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Process interrupted at iteration", ind)
    else:
        print("Process completed.")
    finally:   
        print("Value of the walk was: ", walk)
        return walk

random_walk()

Process interrupted at iteration 10217575
Value of the walk was:  -2601


-2601

## Problem 3 and Problem 4

In [22]:
class ContentFilter():
    """
    
    Attributes:
        filename (str): the name of the file to be read
        contents (str): the contents of the file "filname"
        totalChar (int): the total number of characters in the file
        totalAlph (int): the total number of letters in file
        totalNum (int): the total number of digits in file
        totalSpaces (int): the total number of spaces in file
        totalLines (int): the total number of lines in file
        
     """
    
    def __init__(self, filename):
        """ Construct a file.
        
        Paramters:
            filename (str): the name of the file to read
        
        """
        
        correctFile = False
        self.filename = filename
        
        while not correctFile:
            try:
                myFile = open(self.filename, 'r')
            except FileNotFoundError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            except TypeError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            except OSError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            else:
                correctFile = True
                  
        self.filename = filename
        self.lines = myFile.readlines()
        
        content = ""
        for line in self.lines:
            content += line
            
        self.contents = content
            
        self.totalLines = sum(1 for line in open(filename))
        myFile.close()
        
        
        self.totalChar = len(self.contents)
        self.totalAlph = sum(char.isalpha() for char in self.contents)
        self.totalNum = sum(char.isdigit() for char in self.contents)
        self.totalSpaces = sum(char.isspace() for char in self.contents)
        
    def uniform(self, outfile, mode='w', case='upper'):
        """Write the data to the outfile with uniform case.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            case (str): the case in which the text will be written to outfile; 
                        defaults to 'upper'
            
        """
        
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
        if case not in ['upper', 'lower']:
            raise ValueError("Case must be either upper or lower.")
        try:
            myFileOut = open(outfile, mode)

            if case == "upper":
                for line in self.contents:
                    myFileOut.write(line.upper())
            elif case == "lower":
                for line in self.contents:
                    myFileOut.write(line.lower())
        finally:
            myFileOut.close()
            
    def reverse(self, outfile, mode='w', unit='line'):
        """Write the data to the outfile in reverse order.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            unit (str): If unit="word", reverse the ordering of the words in each line, 
                        but write the lines in the same order as the original file. 
                        If unit="line", reverse the ordering of the lines, 
                        but do not change the ordering of the words on each individual line. 
                        If unit is not one of these two values, raise a ValueError. 
                        Defaults to "line."
            
        """    
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
        
        if unit not in ["line", "word"]:
            raise ValueError("unit must be either line or word")
            
        try:
            myFileOut = open(outfile, mode)

            if unit == "line":
                for i in range(len(self.lines)):
                    myFileOut.write(self.lines[-(i+1)])
            elif unit == "word":
                for line in self.lines: 
                    words = line.split()
                    line_rev = " ".join(reversed(words)) + '\n'
                    myFileOut.write(line_rev)
        finally:
            myFileOut.close()       
        
    def transpose(self, outfile, mode='w'):
        """Write a transposed version of the data to the outfile.
        This means writing the first word of each line of the data to the
        first line of the new file, the second word of each line of the data
        to the second line of the new file, and so on. 
        
        We assume that there are an equal number of words on each line
        of the input file.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            
        """   
        
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
            
        try:
            myFileOut = open(outfile, mode)
            wordMat = []
            
            for line in self.lines:
                words = line.split()
                wordMat.append(words)
            
            wordMat2 = np.array(wordMat)
            wordMatT = wordMat2.T
            
            for row in wordMatT:
                nextline = " ".join(row)
                myFileOut.write(nextline + "\n")
            
        finally:
            myFileOut.close()
        
    def __str__(self):
        """Returns a string with characters of the file."""
        
        string = ("Source file:\t\t\t" + self.filename +
                 "\nTotal characters:\t\t" + str(self.totalChar) +
                 "\nAlphabetic characters:\t\t" + str(self.totalAlph) +
                 "\nNumerical characters:\t\t" + str(self.totalNum) +
                 "\nWhitespace characters:\t\t" + str(self.totalSpaces) +
                 "\nNumber of lines:\t\t" + str(self.totalLines))
        
        return string

In [23]:
cf1 = ContentFilter("test.txt")
cf1.uniform("uniform.txt", case="lower")
cf1.reverse("reverse.txt", unit="word")
cf1.transpose("transpose.txt")